export const AppSettings = {
  FILTER_DATE_FORMAT: 'MMM dd yyyy',
  DATE_FORMAT_MONTH: 'dd MMM yyyy',
  DATE_FORMAT: 'MM/dd/yyyy',
  DATE_FORMAT_TIME: 'dd MMM yyyy h:mm a',
  PIPE_DATE_FORMAT: 'MM/dd/yyyy',
  MOMENT_DATE_FORMAT: 'MM/DD/YYYY',
  MOMENT_DASH_FORMAT: 'MM-DD-YYYY',
  QUARTER_DATE: 'Qo YY',
  QUARTER_DATE_LONG: 'Qo YYYY',
  WEEK_PICKER_FORMAT: 'Week w, yyyy',
  SHORT_MONTH_FORMAT: 'MMM YY',
  SHORT_YEAR_FORMAT: 'YYYY',
  MMM_D: 'MMM d',
  MMM_D_Y: 'MMM d, y',
  D_MMM_Y: 'd MMM y',
  attachmentSupportedFormats: ['.docx', '.doc', '.xlsx', 'xls', '.pptx', '.ppt'],
  dateFormats: ['dd/MM/yyyy', 'MM/dd/yyyy', 'yyyy-MM-dd', 'dd MMM yyyy'],
  generalSettingsKey: 'general_settings',
  storageKey: 'storage',
  defaultFormats: ['application/pdf', 'image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'image/tiff'],
  defaultExtensions: ['.pdf', '.jpeg', '.png', '.tiff', '.gif', '.bmp'],
  documentFormats: ['application/pdf', 'image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'image/tiff',
        'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
  documentExtensions: ['.pdf', '.jpeg', '.png', '.tiff', '.gif', '.bmp', '.doc', '.docx', '.xls', 'xlsx', '.ppt', '.pptx'],
  migrationFormats: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'text/csv', 'text/x-csv', 'application/csv', 'application/x-csv', 'text/comma-separated-values',
        'text/x-comma-separated-values', '.csv'],
  migrationExtensions: ['.xlsx', '.csv'],
  specialKeys: ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Backspace', 'Delete', 'Shift', 'Control', 'Meta', 'Tab', 'Home', 'End'],
  PROFILE_PHOTO_PLACEHOLDER: 'assets/images/profile-photo-placeholder.png',
  PROJECT_PHOTO_PLACEHOLDER: 'assets/images/upload_img.png',
  DEFAULT_PLACEHOLDER: 'assets/images/placeholder-image.png',
  EMPLOYEE_DEFAULT_PICTURE: 'assets/images/default_avatar.png',
  VOLO_LOGO: 'assets/images/volo_logo.png',
  CERTIFICATION_LOGO: 'assets/images/certification_logo.png',
  MAX_INTEGER_VALUE: '2147483647',
  MIN_DATE: new Date(1800, 0, 1),
  MAX_DATE: new Date(2100, 11, 31),
  TIME_OFF_CALENDAR_MIN_WIDTH : 35,
  SCREEN_XL_BREAKPOINT: 1200,
  SCREEN_L_BREAKPOINT: 1024,
  SCREEN_LG_BREAKPOINT: 992,
  SCREEN_MD_BREAKPOINT: 768,
  SCREEN_SM_BREAKPOINT: 576,
  POPUP_INTERVAL: 30 * 60 * 1000, // 30 min
  CHECKING_INTERVAL: 1 * 30 * 1000 // 30 sec
};
